---
apiVersion: v1
kind: Namespace
metadata:
  name: abm-user-cluster-002
---
apiVersion: baremetal.cluster.gke.io/v1
kind: Cluster
metadata:
  name: user-cluster-002
  namespace: abm-user-cluster-002
spec:
  type: user
  kubevirt:
    useEmulation: true
  anthosBareMetalVersion: ABM_VERSION
  gkeConnect:
    projectID: PROJECT_ID
  controlPlane:
    nodePoolSpec:
      clusterName: user-cluster-002
      nodes:
      - address: 10.200.0.11
  clusterNetwork:
    pods:
      cidrBlocks:
      - 192.168.0.0/16
    services:
      cidrBlocks:
      - 172.26.232.0/24
  loadBalancer:
    mode: bundled
    ports:
      controlPlaneLBPort: 443
    vips:
      controlPlaneVIP: 10.200.0.100
      ingressVIP: 10.200.0.101
    addressPools:
    - name: pool1
      addresses:
      - 10.200.0.101-10.200.0.120
  clusterOperations:
    # might need to be this location
    location: us-central1
    projectID: PROJECT_ID
  storage:
    lvpNodeMounts:
      path: /mnt/localpv-disk
      storageClassName: node-disk
    lvpShare:
      numPVUnderSharedPath: 5
      path: /mnt/localpv-share
      storageClassName: standard
  nodeConfig:
    podDensity:
      maxPodsPerNode: 250
    containerRuntime: containerd
---
apiVersion: baremetal.cluster.gke.io/v1
kind: NodePool
metadata:
  name: user-cluster-002-node-pool-1
  namespace: abm-user-cluster-002
spec:
  clusterName: user-cluster-002
  nodes:
  - address: 10.200.0.12