substitutions:
  "_CLUSTER_NAME": "hybrid-cluster-001"
  "_MANIFEST_PATH": "anthos-features/cloudbuild/gke-connect-gateway/example-app.yaml"
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: /bin/sh
  id: Deploy to an ABM cluster
  args:
  - '-c'
  - |
    set -x && \
    export KUBECONFIG="$(pwd)/gateway-kubeconfig" && \
    gcloud beta container hub memberships get-credentials ${_CLUSTER_NAME} && \
    cat $KUBECONFIG && \
    kubectl --kubeconfig gateway-kubeconfig apply -f ${_MANIFEST_PATH}