---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: gateway-impersonate
rules:
- apiGroups:
  - ""
  resourceNames:
  - example-user@google.com
  - PROJECT_NUMBER@cloudbuild.gserviceaccount.com
  - cloud-build-hybrid-workload@benhuston-abm.iam.gserviceaccount.com
  resources:
  - users
  verbs:
  - impersonate

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-impersonate
roleRef:
  kind: ClusterRole
  name: gateway-impersonate
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: connect-agent-sa
  namespace: gke-connect

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gateway-cluster-admin
subjects:
- kind: User
  name: example-user@google.com
- kind: User
  name: PROJECT_NUMBER@cloudbuild.gserviceaccount.com
- kind: User
  name: cloud-build-hybrid-workload@benhuston-abm.iam.gserviceaccount.com
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io