apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cloudbuild-default-role
  namespace: cloudbuild
rules:
- apiGroups:
  - ""
  resources:
  - serviceaccounts/token
  verbs:
  - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cloudbuild-default-admin
  namespace: cloudbuild
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cloudbuild-default-role
subjects:
- kind: ServiceAccount
  name: default
  namespace: cloudbuild